trigger:
- main
 
pool:
  name: 'Default'
  vmImage: ubuntu-latest
  demands:
    - agent.name -equals $(SELF_HOSTED_AGENT_NAME)
steps:
- task: vercel-deployment-task@1
  inputs:
    vercelProjectId: 'prj_ezUM5BbY18eu4c54AEuo7AM0LnZY' 
    vercelOrgId: '6K3TwSsOjOhLot1JgAjiiWAa' 
    vercelToken: $(VERCEL_TOKEN)
    production: true