export const defaultMaintenance = [
	"Revisão 20 mil km",
	"Revisão 30 mil km",
	"Revisão 40 mil km",
	"Revisão 50 mil km",
	"Revisão 60 mil km",
	"Revisão 70 mil km",
	"Troca de óleo e filtro do motor",
	"Revisão do sistema de freios",
	"Revisão do sistema de suspensão",
	"Revisão do sistema elétrico (bateria)",
	"Revisão do sistema de ignição (velas)",
	"Revisão de câmbio manual",
	"Revisão de câmbio automático",
	"Revisão do sistema de injeção eletrônica",
	"Limpeza dos bicos injetores",
	"Descarbonização das válvulas e dutos de admissão",
	"Troca do filtro de ar de admissão",
	"Troca do líquido de arrefecimento",
	"Rodízio de pneus",
	"Alinhamento e balanceamento",
	"Outros",
];
